# Generated by Django 5.2.8 on 2025-11-29 22:14

import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], help_text='The current status of the issue after this update', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this progress update', null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(help_text='The issue this progress update is related to', on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='issue.issue')),
                ('updated_by', models.ForeignKey(help_text='The staff member who made this progress update', on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Update',
                'verbose_name_plural': 'Progress Updates',
                'db_table': 'progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image related to the progress update', upload_to=progress.models.progress_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(help_text='The progress update this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='progress.progress')),
            ],
            options={
                'verbose_name': 'Progress Image',
                'verbose_name_plural': 'Progress Images',
                'db_table': 'progress_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
