# Generated by Django 5.2.8 on 2025-12-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the category (e.g., 'Potholes')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category', null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The title of the issue (e.g., 'Pothole on Main St.')", max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the issue')),
                ('location', models.CharField(help_text='The location where the issue was observed', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='The current status of the issue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category of the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.category')),
                ('reported_by', models.ForeignKey(help_text='The user who reported this issue', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'db_table': 'issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image related to the issue', upload_to='issue_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(help_text='The issue this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issue.issue')),
            ],
            options={
                'verbose_name': 'Issue Image',
                'verbose_name_plural': 'Issue Images',
                'db_table': 'issue_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
