# Generated by Django 5.2.8 on 2025-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road_damage', 'Road Damage / Potholes'), ('road_construction', 'Road Construction Issue'), ('bridge_damage', 'Bridge Damage'), ('footpath_damage', 'Footpath / Sidewalk Damage'), ('speed_bump', 'Speed Bump Required'), ('garbage_pile', 'Garbage Pile / Littering'), ('garbage_collection', 'Garbage Collection Issue'), ('illegal_dumping', 'Illegal Dumping'), ('overflowing_bins', 'Overflowing Bins'), ('dead_animal', 'Dead Animal Removal'), ('water_leak', 'Water Leakage'), ('water_supply', 'Water Supply Issue'), ('drainage_blockage', 'Drainage / Sewer Blockage'), ('flooding', 'Flooding / Waterlogging'), ('open_manhole', 'Open Manhole'), ('street_light', 'Street Light Not Working'), ('power_outage', 'Power Outage'), ('damaged_pole', 'Damaged Electric Pole'), ('exposed_wires', 'Exposed / Dangerous Wires'), ('park_maintenance', 'Park Maintenance'), ('playground_damage', 'Playground Equipment Damage'), ('bench_damage', 'Public Bench Damage'), ('tree_fallen', 'Fallen Tree / Branch'), ('overgrown_vegetation', 'Overgrown Vegetation'), ('traffic_signal', 'Traffic Signal Malfunction'), ('missing_sign', 'Missing / Damaged Sign'), ('road_marking', 'Faded Road Markings'), ('parking_violation', 'Illegal Parking'), ('stray_animals', 'Stray Animals'), ('abandoned_vehicle', 'Abandoned Vehicle'), ('unsafe_building', 'Unsafe / Dangerous Building'), ('noise_complaint', 'Noise Complaint'), ('encroachment', 'Encroachment / Illegal Construction'), ('public_toilet', 'Public Toilet Issue'), ('bus_stop_damage', 'Bus Stop Damage'), ('public_tap', 'Public Tap / Water Point Issue'), ('air_pollution', 'Air Pollution'), ('water_pollution', 'Water Body Pollution'), ('mosquito_breeding', 'Mosquito Breeding'), ('other', 'Other')], default='other', help_text='Category of the issue', max_length=50),
        ),
    ]
