# Generated by Django 5.2.8 on 2025-12-02 17:39

import django.db.models.deletion
import issue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes for this issue'),
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The uploaded image file', upload_to=issue.models.issue_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(help_text='The issue this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issue.issue')),
            ],
            options={
                'verbose_name': 'Issue Image',
                'verbose_name_plural': 'Issue Images',
                'db_table': 'issue_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
