# Generated by Django 5.2.6 on 2025-09-30 06:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_profile_image_path
            ),
        ),
    ]
