# Generated by Django 5.2.6 on 2025-10-30 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be between 7-13 digits",
                        regex="^\\+?\\d{7,13}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number can only contain digits or a plus sign.",
                        regex="^[+\\d]+$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must not contain consecutive special characters.",
                        regex="^\\+?\\d+$",
                    ),
                ],
            ),
        ),
    ]
