# Generated by Django 5.2.8 on 2025-11-29 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('issue', models.ForeignKey(help_text='The issue this comment is related to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issue.issue')),
                ('user', models.ForeignKey(help_text='The user who made this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
